version: '3.9'

services:
  mock-server:
   image: jamesdbloom/mockserver:mockserver-5.4.1
   ports:
    - 1080:1080
   environment:
    - LOG_LEVEL=INFO
    
  mock-code:
   build: 
    context: .
    network: host

  ngrok:
    image: shkoliar/ngrok:latest
    ports: 
      - 4551:4551
    links:
      - mock-server
    environment:
      - DOMAIN=mock-server
      - PORT=1080
